### ISSUE TITLE
iPhone 4 Crash

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic2#643] opened 2015-11-25 11:12 UTC
Should an app I develop with Ionic 2 work on an iPhone 4?  My application crashes when my two iPhone 4 users open it.  It's fine on the iPhone 4S but not on the 4.

**Comment by adamdbradley** [comment] 2015-11-25 13:09
It should work on iPhone 4. What version of iOS do they have?

**Comment by richardshergold** [comment] 2015-11-25 13:13
One of them is iOS version 7.1.2 (11D257) just checking on the other one...

**Comment by richardshergold** [comment] 2015-11-25 13:15
The other is 7.1.2 as well.

**Comment by adamdbradley** [comment] 2015-11-25 13:18
Thanks for the report, we'll look into why it's not working on iOS 7.

**Comment by richardshergold** [comment] 2015-11-26 19:36
I also have an iPhone 5s user who also experiences a crash when the app loads.  All other iPhone 5S users are having no problems at all.  However, she is on iOS 8.1 and they are on 9.  Can you re-produce this (and also the iOS 7 crash) ?

**Comment by richardshergold** [comment] 2015-12-02 10:29
Hi Adam.  Is this definitely a known issue at your end?  If it is, is it likely to fixed any time soon?

**Comment by wulfsolter** [comment] 2015-12-05 13:38
@richardshergold what's the bare minimum needed to crash? Does a fresh clean "blank" project crash? Or "tutorial"?

**Comment by richardshergold** [comment] 2015-12-07 16:45
I've not tried a blank project with these users.  Mine is a tabbed project (pretty similar to the Conference app in structure).  I was really just after some feedback on whether there are any known issues with iOS7 or iOS8.

**Comment by richardshergold** [comment] 2016-01-08 15:35
@adamdbradley I release a version of my app using alpha47 yesterday.  One of my users who was experiencing the crash (iPhone5 with iOS 8) now reports that the app is now working.  The other use (who was an iPhone 4 user) is not in until Monday but I will get her to check then.  The previous version of the app was using alpha40.  I will let you know on Monday if it works for her.

**Comment by richardshergold** [comment] 2016-01-11 11:37
@adamdbradley ok - my iPhone 4 user (running iOS7) now no longer experiences a crash.  So that's good news.  However, there is an issue with screen-layout.  I will e-mail you a screenshot.

**Comment by adamdbradley** [comment] 2016-01-11 14:49
Awesome, that's great to hear. My guess is it's something Angular2 fixed internally, or maybe some polyfill wasn't being used within Angular2 yet.

As far as the layout issue, my guess would be it's a flexbox issue that iOS 7 may have a problem with.

**Comment by Ionitron** [comment] 2016-01-14 17:32
Greetings @richardshergold!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using Ionic, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2016-01-14 17:32 UTC
Labels: ionitron:closed, v2
