### ISSUE TITLE
Label overlaps input field after navigation

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [driftyco/ionic2#655] opened 2015-11-26 21:30 UTC
Hi, when using floating labels, when you type something the label goes up, nice. Then if you change the route and then comes back to the route where you typed, the text in the input is still there but the label isn't on the top, it's on the original position, overlapping the input's text

**Comment by brandyscarney** [comment] 2015-12-08 18:50
This is caused by the `has-value` class not being applied to the `ion-input`.

**Comment by brandyscarney** [comment] 2015-12-10 20:47
Confirmed this was fixed by #710. It will be in the next release, alpha.41, which we plan on doing later today. Please take a look at our changelog for some other major changes in this release.

**Closed** 2015-12-10 20:47 UTC
Labels: bug, P2: required
