### ISSUE TITLE
ionic generators broken in alpha.46

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#876] opened 2016-01-06 15:59 UTC
I started a new project as today 06/01/2016 and the generate command is broken, i'm using alpha.46 and the output suggest an error in the creation of the files, both the path and the creation of the file itself, the output is:
>$ ionic g page test
√ Create app/test/test.html
Error with generation: { [Error: ENOENT: no such file or directory, open '/home/carlos/Carlos/Programming/OSGroup/buildTest2/app/test/test.html']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/carlos/Carlos/Programming/OSGroup/buildTest2/app/test/test.html' }
Error: ENOENT: no such file or directory, open '/home/carlos/Carlos/Programming/OSGroup/buildTest2/app/test/test.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at /home/carlos/Carlos/Programming/OSGroup/buildTest2/node_modules/ionic-framework/tooling/generate.js:83:8
    at Array.forEach (native)
    at Object.defaultTemplates (/home/carlos/Carlos/Programming/OSGroup/buildTest2/node_modules/ionic-framework/tooling/generate.js:76:13)
    at Object.generate (/home/carlos/Carlos/Programming/OSGroup/buildTest2/node_modules/ionic-framework/tooling/generate.js:60:23)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/generate.js:62:28)
    at Promise.apply (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:741:41)

**Comment by mhartington** [comment] 2016-01-06 16:02
Duplicate of https://github.com/driftyco/ionic2/issues/824

**Closed by mhartington** 2016-01-06 16:02 UTC

**Comment by Luchillo** [comment] 2016-01-06 18:39
It's not just the folder structure, now they don't even work, they try to create the app folder along with the folder for the page or injectable folder but the file, be it html or js doesn't get created, just show the message above, that's why i made another issue.
