### ISSUE TITLE
Set typings files (.d.ts) for ionic/ionic

### ISSUE THREAD

**Issue by hlehmann** [driftyco/ionic2#360] opened 2015-10-28 12:52 UTC
With webstorm I can't have the typing information for ionic2.
`tsd install ionic/ionic` seems to be for ionic 1.x

**Comment by mhartington** [comment] 2015-10-28 14:17
Duplicate of #84

**Closed by mhartington** 2015-10-28 14:17 UTC

**Comment by jksoftpro** [comment] 2015-11-25 22:48
For anyone looking for Ionic2 Type Definition please follow this link:
https://github.com/jksoftpro/ionic2-seed/blob/master/tools/typings/ionic2.d.ts

I created this one for version "ionic-framework": "2.0.0-alpha.36". It works well for me. I hope it will help.
