### ISSUE TITLE
alpha.45 breaks sidemenu app

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#803] opened 2015-12-23 16:35 UTC
I created a test app to get the latest package.json along with trying to update other files like the webpack.config.js, i did it successfully but now i have an issue, my updated app has sidemenus, they work fine, for the first click, after that the backdrop doesn't go away and i cant click anything inside the app, if i remove the backdrop html element from chrome dev tools, it works as expected, even after multiple component navigation changes.

This issue doesn't happen in the test sidemenu app, nor in my app before update.

**Comment by Luchillo** [comment] 2015-12-23 16:58
Found the issue, even the starter sidemenu app breaks but only when inside emulation tool of chrome, when i'm emulating a devise with chrome dev tools the starter sidemenu app breaks and doesn't remove the backdrop from the sidemenu.

**Comment by gcrockenberg** [comment] 2015-12-24 13:10
I ran into this.  Had to comment out 'transforms.push('translateZ(0px)');' from the animation script to get it working again.  I'm not sure why those translations are being added dynamically by ionic but they cause this issue to arise when I run in Android mode in Ripple in my Cordova app in Visual Studio.  Try commenting them out in the Ionic bundle.  There are two such instances.

**Comment by abbazabacto** [comment] 2015-12-24 15:41
I was playing around with the tutorial starter app with ionic@beta (angular2.0.0-beta.0 and ionic2.0.0-alpha.45). Like @Luchillo mentioned, after opening the menu and closing it again, the backdrop on an Android (real and emulated) device remains (invisibly) overlapping on screen and making it impossible to interact with the underlaying app (with every touch/click the console.log kept logging *backdrop clicked*).

@gcrockenberg Thanks for that tip, at least I can continue now.. 
I believe adding transLateZ is done to force hardware acceleration... 
For me I only had to comment out the following to make it work (so not the `transforms.push(translateZ(0px))`)
node_modules/ionic-framework/animations/animation.js#L638
`ele.style[dom_1.CSS.transform] = 'translateZ(0px)';`

In ionic/animations/animation.ts in the ionic2 repo that would be:
`ele.style[CSS.transform] = 'translateZ(0px)';`

**Comment by gcrockenberg** [comment] 2015-12-24 15:58
Confirming that commenting only 
ele.style[CSS.transform] = 'translateZ(0px)'; 

works for me to address the issue.  Thanks.

**Comment by Luchillo** [comment] 2015-12-25 17:13
Ok @gcrockenberg  this is a workaround, thanks but have you filled a pull request for this error?

**Comment by mhartington** [comment] 2015-12-26 01:45
Confirmed. Thanks for pointing this out :+1:

**Closed** 2015-12-28 17:22 UTC
Labels: in progress, P0: critical

**Comment by brandyscarney** [comment] 2015-12-28 17:24
Thanks for finding the fix! I didn't see any negative results of removing this code in any of my tests, so it will be in the next release. :+1:

**Comment by adamdbradley** [comment] 2015-12-31 04:17
It was there to ensure an animation that's changing only opacity happening has been given a new layer so the GPU can easily change the opacity. But yes it causes other issues like this. So keep an eye on any jank on low performing devices for animations only changing opacity. Probably have to add translateZ(0) css on each of the elements that would use this type of animation if we see any issues.
