### ISSUE TITLE
ionic serve does not create css file

### ISSUE THREAD

**Issue by dmastag** [driftyco/ionic2#575] opened 2015-11-18 00:39 UTC
On the Tutorial Template, the scss to css process is not running.
And in the Build folder there is no css file. But the app is working somehow.

```
Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
OS:
Node Version: v5.0.0
```

![image](https://cloud.githubusercontent.com/assets/5745805/11229354/11debc08-8dc7-11e5-9fd5-e5b41a02fbd9.png)

**Comment by ajaybeniwal** [comment] 2015-11-18 10:45
+1

**Comment by ajaybeniwal** [comment] 2015-11-18 10:52
C:\OfficeWork\b2bmobile\Hybrid>gulp sass
[18:51:06] Using gulpfile C:\OfficeWork\b2bmobile\Hybrid\gulpfile.js
[18:51:06] Starting 'sass'...
www\app\app.scss
  26:1  File to import not found or unreadable: ionic
Parent style sheet: stdin
[18:51:06] Finished 'sass' after 26 ms

**Comment by ajaybeniwal** [comment] 2015-11-18 10:53
I created the the project in Ionic alpha 31 but upgrading to 33 facing all kind of issues

**Comment by tlancina** [comment] 2015-11-18 15:43
@dmastag [webpack treats the Sass/CSS as a dependency](http://webpack.github.io/docs/what-is-webpack.html#loaders) just like the JS/TS files and includes it in the bundle.  If you take a look at app.js you'll see that the Sass is imported as well.  A little strange I know, but there are a lot of positives to this approach.

If you want to generate an external css file, you can either remove the Sass imports in your JS files and use a separate gulp task, or this webpack plugin: https://github.com/webpack/extract-text-webpack-plugin.  We might add this plugin for production builds, but for development it's better to leave the Sass imports, since then changes will only cause the stylesheet for a specific module to be rebuilt instead of having to completely rebuild one giant app.css file.

Closing this since it is intended behavior.

**Closed by tlancina** 2015-11-18 15:43 UTC

**Comment by dmastag** [comment] 2015-11-18 16:12
No problem and thanks for the explanation @tlancina , feels much better now that I know how it is supposed to work.
