### ISSUE TITLE
more text input padding after label

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#499] opened 2015-11-12 21:54 UTC
http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/a4n3/chrome_400x800#a40bc7d6

![image](https://cloud.githubusercontent.com/assets/452425/11132466/b111f2f2-8955-11e5-93bd-a306c2ccad85.png)

**Comment by brandyscarney** [comment] 2015-11-12 22:29
Duplicate of #498

**Closed by brandyscarney** 2015-11-12 22:29 UTC
