### ISSUE TITLE
ionic generate command not working

### ISSUE THREAD

**Issue by blackecho** [driftyco/ionic2#779] opened 2015-12-18 21:29 UTC
ionic cli command "generate" is not working. It outputs the following error:

    You do not appear to have a compatible version of Ionic v2 installed.
    Ionic Framework v2 version 2.0.0-alpha.31 or later is required to use the generators.
    Please run: "npm install ionic-framework" (CLI v2.0.0-beta.11)

    Your system information:

    Cordova CLI: 5.4.1 
    Gulp version:  CLI version 3.9.0 
    Gulp local:   Local version 3.9.0
    Ionic Version: 2.0.0-alpha.42
    Ionic CLI Version: 2.0.0-beta.11
    Ionic App Lib Version: 2.0.0-beta.5
    OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
    Node Version: v4.0.0

The error says that version alpha.31 or later is required, but I have version alpha.42. I think this is a problem with the cli. In fact, if run the following code from a node console, it works fine:

    var ionic = require('ionic-framework');
    ionic.generate({ appDirectory: process.cwd(), generator: 'page', name: 'my-page' });

**Comment by mhartington** [comment] 2015-12-18 21:31
Duplicate of #756

**Closed by mhartington** 2015-12-18 21:31 UTC
