### ISSUE TITLE
Angular 2 Component not showing

### ISSUE THREAD

**Issue by prolink007** [driftyco/ionic2#683] opened 2015-12-02 15:10 UTC
I am trying to show an `OAuthComponent` in my `GettingStartedPage` component. The `OAuthComponent` is not showing up when served to my browser. No errors.

Stack post http://stackoverflow.com/q/34031481/427763

---

    OAuthComponent.ts
    
    import {Page, NavController} from 'ionic/ionic';
    import {Component} from 'angular2/angular2'
    
    @Component({
        templateUrl: "app/authentication/components/oauth-component.html",
        selector: "oauth-component"
    })
    export class OAuthComponent {
    
        private nav: NavController;
    
        constructor(nav: NavController) {
            this.nav = nav;
        }
    }

---

    oauth-component.html
    
    <h1>
        Testing Something
    </h1>

---

    GettingStartedPage.ts
    
    import {Page, NavController} from 'ionic/ionic';
    import {OAuthComponent} from "../authentication/components/OAuthComponent";
    import "./getting-started.scss";
    
    @Page({
        templateUrl: 'app/getting-started/getting-started.html',
        directives: [OAuthComponent]
    })
    export class GettingStartedPage {
    
        private nav: NavController;
    
        constructor(nav: NavController) {
            this.nav = nav;
        }
    }

---

    getting-started.html
    
    <ion-navbar *navbar>
        <a menu-toggle>
            <icon menu></icon>
        </a>
    
        <ion-title>Getting Started</ion-title>
    </ion-navbar>
    
    <ion-content>
        <main>
            <oauth-component></oauth-component>
        </main>
    </ion-content>

**Comment by prolink007** [comment] 2015-12-02 15:34
I have been using `ionic serve` to serve this to my browser for testing. And it has not been working. A few minutes ago, i was helping someone else here on github with a different issue and tried running TSC on my project. After i finished helping them, i ran `ionic serve` again and it is now working. What was the deal? Why did running TSC independently of `ionic serve` seem to fix the issue?

**Comment by mhartington** [comment] 2015-12-02 15:44
It's not, all the build tools are included when you get a project. I created a similar project here

https://github.com/mhartington/ionic2-component-test/tree/master/www/app

Which is a close copy of what you have provided, but wasn't able to replicate your issue. 
If you clone the project, run npm install then ionic serve, you should see hello world on the screen.

At no time did I stop to run `TSC`, ionic serve handled everything. 
Is there anymore information you could provide? Maybe a minimal example in a git repo I could look at?

**Comment by prolink007** [comment] 2015-12-02 15:46
The only difference is that "GettingStartedPage" is not my "app.js". It is a `Page` that is included in the `app.js` and the `OAuthComponent` is a few directories below the `GettingStartedPage`. The only difference i did when building and serving was running `TSC` outside of `ionic serve` in between builds one time. Now everything seems to be working.

**Comment by mhartington** [comment] 2015-12-02 15:49
Right, and in this example, 'GettingStarted' is my Home page. 

Can you post your `ionic info`. You shouldn't have to run TSC ever outside of ionic serve so maybe it's a tooling problem. Could you still push an example up for to look at? I should be able to resolve this faster with it.

**Comment by prolink007** [comment] 2015-12-02 15:52
I am not able to push an example. =(

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.38
Ionic CLI Version: 2.0.0-alpha.25
Ionic App Lib Version: 2.0.0-alpha.24
OS: Windows 7 SP1
Node Version: v5.1.0

Global npm packages
├── cordova@5.4.1
├── ionic@2.0.0-alpha.25
├── npm@3.5.0
├── npm-check-updates@2.5.1
├── python@0.0.4
└── typescript@1.7.3

Project npm packages
├── autoprefixer-loader@3.1.0
├── awesome-typescript-loader@0.12.0-rc.2
├── css-loader@0.23.0
├── file-loader@0.8.5
├── ionic-framework@2.0.0-alpha.38
├── node-sass@3.4.2
├── resolve-url-loader@1.4.2
├── sass-loader@3.1.2
├── style-loader@0.13.0
├── typescript@1.5.3
├── url-loader@0.5.7
└── webpack@1.12.9

**Comment by mhartington** [comment] 2015-12-02 16:18
Okay, could you fork the project I posted and make it structured similarly to yours? As it stands, I can't seem to replicate this so I'm not sure where the issue is.

**Comment by prolink007** [comment] 2015-12-02 16:23
When i get the chance, i will try to do that and see if i can re-produce the issue. Thanks

**Comment by mhartington** [comment] 2015-12-07 14:49
@prolink007 Any progress on getting an example together?

**Comment by prolink007** [comment] 2015-12-07 14:57
@mhartington Sorry, was really busy last week and over the weekend. We are on a pretty tight schedule at the moment and i have not had a lot of free time to get this worked up. Hopefully i can get to it this week. Thanks for reminding me. =)

**Comment by mhartington** [comment] 2015-12-07 15:04
Sounds good. Going to close this for now then. When you have an example that I can look at, ping me and I'll open this again. Cheers.

**Closed by mhartington** 2015-12-07 15:04 UTC
