### ISSUE TITLE
Issue in Navgiation to child page if keyboard is open (bottom tab par)

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#435] opened 2015-11-04 03:27 UTC
I have a top search bar with list view below that, the navigation problem comes when the keyboard is open and I am typing into the search bar to filter the list view  results  so when you click on list and navigate to inner  page for partial of second you will see the tab bar jump to the middle of the screen  which looks janky (I am testing only on IOS)

**Comment by adamdbradley** [comment] 2016-01-04 17:54
From some recent fixes for other issues, after a transition, if a keyboard is still open it'll close it down. Is this still an issue with the latest version?

**Comment by frederikschubert** [comment] 2016-01-04 17:56
From what I can see the error is gone.

**Comment by Ionitron** [comment] 2016-01-14 17:32
Greetings @ajaybeniwal!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using Ionic, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.

**Closed by Ionitron** 2016-01-14 17:32 UTC
Labels: ionitron:closed, v2
