### ISSUE TITLE
Webpack module dependency on beta.15

### ISSUE THREAD

**Issue by arthurbragaa** [driftyco/ionic2#804] opened 2015-12-23 18:12 UTC
I intalled the latest beta version today and after creating the project and run ionic serve,
i was getting this message:

    ∆ Compiling and bundling with Webpack...
    There was an error loading webpack.config.js:

    Error: Cannot find module 'webpack'
        at Function.Module._resolveFilename (module.js:337:15)
        at Function.Module._load (module.js:287:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/home/arthur/Development/ionic/ionic-todo/webpack.config.js:2:15)
        at Module._compile (module.js:435:26)
        at Object.Module._extensions..js (module.js:442:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)

Then i tried:
    npm install 

Then i got this message:

     npm WARN babel-loader@6.2.0 requires a peer of webpack@^1.0.0 but none was installed.
     npm WARN ionic-todo@ No repository field.
     npm WARN ionic-todo@ No license field.

I was able to solve by installing webpack manually.

    npm -g install webpack

**Comment by Luchillo** [comment] 2015-12-23 18:35
You shouldn't install it global, it is a peer dependency of babel-loader, you have to install it manually and save it to package.json, personally i don't like peer dependencies, at least until npm add a `--save-peer` flag to `npm install`

**Comment by kitkimwong** [comment] 2015-12-24 19:12
same problem here... any suggestions?

**Comment by tlancina** [comment] 2016-01-04 16:33
This was caused by a leftover webpack `require` I believe, and should be fixed in the latest starters.

**Closed by tlancina** 2016-01-04 16:33 UTC
