### ISSUE TITLE
ngIf in icon breaks then item-right attribute

### ISSUE THREAD

**Issue by phavre** [driftyco/ionic2#841] opened 2016-01-01 14:20 UTC
When using a ngIf in an ion-item / icon element then item-right is ignored.
Remove the ngIf and the icon is right aligned.

`<ion-item>List <icon heart item-right *ngIf="true" ></icon></ion-item>`
![image](https://cloud.githubusercontent.com/assets/16475287/12071126/f206102e-b09a-11e5-81d4-b6a5e64b4fd4.png)

`<ion-item>List <icon heart item-right></icon></ion-item>`
![image](https://cloud.githubusercontent.com/assets/16475287/12071131/189d2f9c-b09b-11e5-9d86-abafd43cd6af.png)

version:
Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
OS: Windows 7 SP1
Node Version: v5.3.0

**Comment by brandyscarney** [comment] 2016-01-01 19:12
Duplicate of https://github.com/driftyco/ionic2/issues/574 & there is also a workaround there.

See https://github.com/angular/angular/issues/5363

**Closed by brandyscarney** 2016-01-01 19:12 UTC

**Comment by phavre** [comment] 2016-01-01 19:40
sorry for the duplicate. Anyway happy new year :)

**Comment by brandyscarney** [comment] 2016-01-01 19:45
Not a problem! The issue title was a bit vague so I updated it. Happy New Year! :smile:
