### ISSUE TITLE
fix right side button margin 

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#497] opened 2015-11-12 21:53 UTC
http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/a4n3/chrome_400x800#1299f381

![image](https://cloud.githubusercontent.com/assets/452425/11132412/6ff12a86-8955-11e5-947d-f2162f3b68e3.png)

**Comment by adamdbradley** [comment] 2015-11-12 21:53
Also http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/a4n3/chrome_400x800#9cca14d5

![image](https://cloud.githubusercontent.com/assets/452425/11132432/83d4dd18-8955-11e5-9c9c-5d99bbb0e1ce.png)

**Comment by brandyscarney** [comment] 2015-11-12 21:57
This is a duplicate of #495

**Closed by brandyscarney** 2015-11-12 21:57 UTC
