### ISSUE TITLE
collection-repeat

### ISSUE THREAD

**Issue by qiongshusheng** [driftyco/ionic2#921] opened 2016-01-11 02:01 UTC
list-infinite demo: EXCEPTION: No provider for ProtoViewRef! (ItemCellTemplate -> ProtoViewRef)

infinite\index.ts
import {ProtoViewRef, ViewContainerRef} from 'angular2/core'
ProtoViewRef not found from 'angular2/core'

**Comment by mlynch** [comment] 2016-01-13 22:29
Dupe of #382

**Closed** 2016-01-13 22:29 UTC
