### ISSUE TITLE
ngModel not working on ion-checkbox and ion-toggle, have to watch for click event

### ISSUE THREAD

**Issue by colinjlacy** [driftyco/ionic2#842] opened 2016-01-01 19:02 UTC
Hi, I'm having trouble trying to apply the ngModel directive to ion-toggle and ion-checkbox.  If I try the following:

```
<ion-toggle [(ngModel)]="listItem.active">{{listItem.name}}</ion-toggle>
```

I get the this error:

<img width="1026" alt="screen shot 2015-12-31 at 11 06 55 am" src="https://cloud.githubusercontent.com/assets/4993605/12071839/3ea2bc20-b087-11e5-8b0b-107674f7b9d3.png">

I was able to get it to work by binding one-way to the `checked` property, and then listening for a `(click)` with a component event handler:

```
<ion-toggle checked="{{listItem.active}}" (click)="toggleActive(listItem)">{{listItem.name}}</ion-toggle>
```

Am I missing something or is this the intended functionality?  And if it is that's totally fine; I'm just wondering if this is the way I should implement going forward.

**Comment by brandyscarney** [comment] 2016-01-01 19:53
The way you had it the first time is the intended way to write it. This is a bug. I think it is the same issue as #819, which I am unable to reproduce in local tests so I believe it has been fixed in a previous refactor. We just need to get a stable release together to find out.

**Comment by phavre** [comment] 2016-01-01 20:24
I Hope this will also solve a similar issue with the searchbar which is not working either for the same reason (object has change after it was checked). Had to bind the list item with a class attribute hidden to filter the non matching lines

**Comment by brandyscarney** [comment] 2016-01-01 20:30
That exception shouldn't be breaking anything. It is being thrown on a lot of components right now but they still work as desired. The issue with this is caused by something else. Can you paste your code for the searchbar and compare it to the conference app? 

https://github.com/driftyco/ionic-conference-app/blob/master/app/pages/schedule/schedule.html#L24-L28
https://github.com/driftyco/ionic-conference-app/blob/master/app/pages/schedule/schedule.js#L36-L41

**Comment by dupski** [comment] 2016-01-02 00:16
+1
I get the exact same exception using ion-toggle with ngControl and a ControlGroup. I have also tried with ion-checkbox and a vanilla checkbox and got similar issues, so I'm wondering if this is an Angular2 problem?

<ion-toggle ngControl="use_ssl">Use SSL?</ion-toggle>

I currently have to use:

<ion-toggle #chk1 [checked]="settingsForm.controls['use_ssl'].value (click)="settingsForm.controls['use_ssl'].updateValue(chk1.checked)">Use SSL?</ion-toggle>

Which ain't pretty! :)

My ionic info:
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v4.2.4

**Comment by colinjlacy** [comment] 2016-01-02 01:07
Yeah it's the same for toggle and checkbox.  Thanks for the quick reply, looking forward to the fix.

**Comment by phavre** [comment] 2016-01-03 20:26
Indeed @brandyscarney when implementing the searchBar the way it has been done in the links you supplied, it works like a charm. 
I originally followed the searchbar component demo source and this one gives me the error (it it functioning ?) I couldn't understand how the getItem function could be called for the view to be refreshed (But in the link provided it was clear with the input bind function)

**Comment by brandyscarney** [comment] 2016-01-04 03:06
The component demos are a little behind master right now. We're constantly changing things in the source code and it's hard to keep the demos up to date all of the time. We try to keep the conference app up to date with the latest stable release and all component test folders should reflect master. For example, the searchbar test folder is here with different test cases:

https://github.com/driftyco/ionic2/tree/master/ionic/components/searchbar/test

And you can follow these instructions to run the source code and view all of the component tests: 

https://github.com/driftyco/ionic2/blob/master/scripts/README.md#building--running-ionic-source

**Comment by DrMabuse23** [comment] 2016-01-04 07:56
On ion-segment same error

**Comment by phavre** [comment] 2016-01-05 16:24
Thanks for the precious advice @brandyscarney I'll focus from now on, on the links provided to help me.
Cheers

**Comment by dupski** [comment] 2016-01-05 16:38
I'll give it a test on the latest build, hopefully later this week or at the weekend at the latest and report back. Thanks :)

**Comment by dupski** [comment] 2016-01-06 11:53
Hi Guys

This issue is still occurring for me with the latest alpha (47) and the following set up:

```
import {FormBuilder, Validators, ControlGroup} from 'angular2/common';
...
export class SettingsPage {
    settingsForm: ControlGroup;

    constructor(
        fb: FormBuilder) {

        this.settingsForm = fb.group({
            host: [null, Validators.required],
            port: [null, Validators.required],
            use_ssl: [],
        });
...
```
And in the template:
```
<form [ngFormModel]="settingsForm" (submit)="saveSettings($event)">
<ion-list>
	<ion-input stacked-label>
		<ion-label>Server Address</ion-label>
		<input type="text" ngControl="host">
	</ion-input>
	<ion-input stacked-label>
		<ion-label>Port</ion-label>
		<input type="text" ngControl="port">
	</ion-input>

	<ion-toggle ngControl="use_ssl">Use SSL?</ion-toggle>
</ion-list>
</form>
...
```
Maybe it is still fixed in latest master, I'll have a play with a checkout at the weekend.

**Comment by brandyscarney** [comment] 2016-01-06 17:14
So for the original issue, this works for `ngModel` to check the toggle by default:

html:

```
<ion-toggle value="apple" [(ngModel)]="myModel">
  I'm an NgModel
</ion-toggle>
```

where the JS is:

```
this.myModel = true;
```

so right now the `ngModel` needs to be a boolean to check by default.

I can see in our use case that the toggle with `ngControl` isn't being checked when it should in this example:

```
<ion-toggle value="apple" checked="true" ngControl="appleCtrl">
  Apple, value=apple, init checked
</ion-toggle>
```

We're going to talk with the Angular team today about this.

**Comment by colinjlacy** [comment] 2016-01-08 01:40
Thanks for your input.  Unfortunately I'm not seeing the same results.  I've got the `ion-toggle` set up as you have it:
```
<ion-toggle value="apple" [(ngModel)]="listItem.active">Active</ion-toggle>
```

My interface says that the value is a boolean:
```
export interface ListItem {
    id: number,
    name: string,
    media: string,
    latitude: string,
    longitude: string,
    active: boolean
}
```

Could it have something to do with the fact that I'm loading the value from a data service instead of a binding attribute?
```
onPageWillEnter() {
    this._service.getItem(this.id).then(item => {
        this.listItem = item;
    });
}
```

**Comment by mhartington** [comment] 2016-01-18 21:36
This issue was moved to driftyco/ionic#5034

**Closed by mhartington** 2016-01-18 21:36 UTC
Labels: bug, P1: urgent, v2
