### ISSUE TITLE
Radio toggles all items when you only tap one

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic2#902] opened 2016-01-09 00:42 UTC
![image](https://cloud.githubusercontent.com/assets/519526/12213066/9ac91a02-b637-11e5-9ca5-a54ac211e8d3.png)

**Comment by brandyscarney** [comment] 2016-01-09 00:56
Possible duplicate of https://github.com/driftyco/ionic2/issues/843

**Comment by adamdbradley** [comment] 2016-01-09 01:49
@drewrygh please set a value for each radio button

**Comment by drewrygh** [comment] 2016-01-09 05:25
After setting a `value` on each toggle, now whenever any toggle is tapped, the last toggle in the list will always be selected.

I checked out the e2e tests and (assuming they work), the only difference is they have an `ngControl` `attribute. Is this required now? I'll look in to it more tomorrow.

**Comment by adamdbradley** [comment] 2016-01-10 04:22
@drewrygh I haven't been able to replicated this

**Closed by adamdbradley** 2016-01-10 04:22 UTC
Labels: docs

**Comment by mauricionarcizo** [comment] 2016-01-10 11:54
Hi!

I have the same problem.
I follow the docs from http://ionicframework.com/docs/v2/components/#radio 
Example code:
<ion-list radio-group>
    <ion-header>
      Language
    </ion-header>

    <ion-radio checked="true" value="go">
      Go
    </ion-radio>

    <ion-radio value="rust">
      Rust
    </ion-radio>

    <ion-radio value="python">
      Python
    </ion-radio>
  </ion-list>
