### ISSUE TITLE
ion-list (item-right and item-left) bug when use with *ngIf

### ISSUE THREAD

**Issue by Doehl** [driftyco/ionic2#849] opened 2016-01-03 18:43 UTC
## Description
When using the attr "item-right" or "item-left" on a icon with the *ngIf, will the "icon" be placed in the "ion-item-content" tag. 
This is not correct behaver, since it should be placed outside the "ion-item-content" tag, either before (left) or after (right) the "ion-item-content" tag.

## Example repository 
https://github.com/Doehl/list-item-right-ngif-bug

## Bug image
![Bug](http://ccpl.dk/github-img/ionic-bug-03012016.png)

#### TypeScript
```
export class Page1 {
    boolVariable: any = true;
  constructor() {

  }
}
```

#### Html
```
<ion-list>
  <ion-item>
    Without *ngIf (Correct)
    <icon checkmark item-right></icon>
  </ion-item>
  <ion-item>
    With *ngIf (BUG)
    <icon *ngIf="boolVariable == true" checkmark item-right></icon>
  </ion-item>
</ion-list>
```

**Comment by brandyscarney** [comment] 2016-01-03 19:08
This is a duplicate of https://github.com/driftyco/ionic2/issues/574. There is a temporary workaround that can be used on that issue. :smile:

**Closed by brandyscarney** 2016-01-03 19:08 UTC
