### ISSUE TITLE
How to setup the project to use TypeScript?

### ISSUE THREAD

**Issue by nampdn** [driftyco/ionic2#653] opened 2015-11-26 09:11 UTC
I don't know how to setup Ionic2 to work with TypeScript, and how to config it with Visual Code.
Currently, I use VSCode to open the project folder. But too much syntax error inside .js file. Don't know where to start despite I went through the official docs. Please help me!

![issue2](https://cloud.githubusercontent.com/assets/15364911/11419512/8b14d92e-945a-11e5-80f7-8b799a7712c9.gif)

**Comment by astec** [comment] 2015-11-26 17:21
Duplicate of #527

**Comment by nampdn** [comment] 2015-11-27 09:34
@astec , I have read that post before I posted this issue. I think they are not same.

**Comment by jgw96** [comment] 2015-11-30 04:40
@nampdn the issues your seeing are caused by the fact that vscode is looking for a jsconfig file instead of the tsconfig file which is included because the file extensions are .js instead of .ts. This is what issue #527 is about, there is also a temporary fix there that will hopefully help you (:

**Comment by tlancina** [comment] 2015-12-14 18:01
With the latest `ionic@beta` you can specify `--ts` to use the Typescript version of a starter: `ionic start myapp --v2 --ts`

**Closed by tlancina** 2015-12-14 18:01 UTC
