### ISSUE TITLE
ion-segment ngModel issue

### ISSUE THREAD

**Issue by phavre** [driftyco/ionic2#838] opened 2015-12-31 22:49 UTC
Maybe duplicate with #819, but the issue is more with valorisation than css class.

When using the ion-segment component with 2 ion-segment-button, the property bound with ngModel is only updated the first time. After that, the focus stays on the same button and the property is no more updated.
![image](https://cloud.githubusercontent.com/assets/16475287/12068848/6b7f0bd8-b017-11e5-9210-230219d3951e.png)
As we see on the image, when clicked on the Dictionary button, the focus stays on Favorites button and hence the property stays at favorite.

The code:
  `<ion-segment [(ngModel)]="filterFavorite" (change)="getDictionary()">`
    `<ion-segment-button value="fals">`
      `{{ 'Dictionary' | translate }}`
    `</ion-segment-button>`
    `<ion-segment-button value="tru">`
      `{{ 'Favorites' | translate }}`
    `</ion-segment-button>`
  `</ion-segment>`

Here's the console logs:

`SegmentButton, select tru;` (button Favorites is clicked)
`getDictionary() called with isFavorite: tru;` (onChange getDictionary() debug log on filterFavorite bind property)
`SegmentButton, select fals;`(button Dictionary is clicked)
`getDictionary() called with isFavorite: tru` (onChange getDictionary() debug log on filterFavorite bind property)

versions:
Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
OS: Windows 7 SP1
Node Version: v5.3.0

**Comment by brandyscarney** [comment] 2016-01-01 19:10
Yes, this is a duplicate of #819.

**Closed by brandyscarney** 2016-01-01 19:10 UTC
