### ISSUE TITLE
Swipeable items show option buttons underneath item content, near hairline

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#295] opened 2015-10-16 03:04 UTC
You can kind of see the blue button on the hairline between items, when the items are closed:

![image](https://cloud.githubusercontent.com/assets/452425/10532882/7a63c7ea-7388-11e5-9c3a-43621844cef3.png)

**Comment by brandyscarney** [comment] 2015-10-20 17:43
@adamdbradley can you confirm I fixed this in the e2e tests? I was only able to see this on the bottom 2 items because of their height. I have not been able to reproduce this in the conf app, so I may have fixed a completely different issue.

![screen shot 2015-10-20 at 12 31 41 pm](https://cloud.githubusercontent.com/assets/6577830/10615910/7418984c-7730-11e5-8b72-932e7c482b29.png)

**Comment by brandyscarney** [comment] 2015-10-27 16:03
Closing per Adam

**Closed by brandyscarney** 2015-10-27 16:03 UTC
