### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic2#878] opened 2016-01-06 18:03 UTC
The Ionic 1 and 2 doesn't include RTL support. You can't choose LTR or RTL app in the configuration.
It would be nice to config direction of app; for arabic and hebrew apps.
Right now I can fix direction from css and dir attribute but some components not working well.

**Comment by brandyscarney** [comment] 2016-01-06 18:07
Duplicate of https://github.com/driftyco/ionic2/issues/832

Please add any input you have on that issue. Thanks! :smile:

**Closed by brandyscarney** 2016-01-06 18:07 UTC
