### ISSUE TITLE
Changes in .ts files trigger rebuilds of webpack bundle, however sometimes the changes don't show up in browser (even with cache disabled)

### ISSUE THREAD

**Issue by NathanWalker** [driftyco/ionic2#938] opened 2016-01-13 01:49 UTC
I'm loving Ionic2 with TypeScript! However, I'm running into a rather frustrating issue where I make a change in any .ts file in the `/app` directory, and the webpack build will trigger a rebuild of the `app.bundle.js` but when the browser (latest Chrome on Mac) refreshes and I look in the Sources, app.bundle.js does not contain the changes that I made?

Am I missing something? Is there something with tsconfig.json? Or with some webpack config?

**Comment by tlancina** [comment] 2016-01-13 04:23
Does your awesome-typescript-loader config in webpack.config.js have the `useWebpackText` query: https://github.com/driftyco/ionic-conference-app/blob/master/webpack.config.js#L24?

It was recently added back in after being accidentally removed :)

**Comment by mhartington** [comment] 2016-01-13 04:24
I have seen this too, even with the `useWebpackText` query included

**Comment by wulfsolter** [comment] 2016-01-14 02:30
Issue still exists with `useWebpackText: true` in `webpack.config.js`.

To recreate: 

1. Create new `ionic start myApp --v2 --ts`
2. `ionic serve` to start
3. Edit a .ts file - e.g. putting `console.log('foo');` inside the constructor `app/pages/page1/page1.ts`
Window reloads, console shows 'foo'
4. Edit the same page1.ts and add a `console.log('bar');` below the first
5. Window reloads again, code has now changed and console shows only `foo` and no `bar`.

**Comment by tlancina** [comment] 2016-01-14 15:23
Yeah I can reproduce it, taking a look at this now.

**Comment by tlancina** [comment] 2016-01-14 15:35
So it looks like `useWebpackText` is actually the culprit for the TypeScript versions, if you remove it does that resolve the issue?

**Comment by wulfsolter** [comment] 2016-01-14 20:23
Confirming. Removing `useWebpackText` from `webpack.config.js` results in subsequent reloads loading fresh code. Thanks @tlancina

**Comment by tlancina** [comment] 2016-01-14 20:31
Awesome, I've just updated the TypeScript starters.  Thanks everyone! Going to close this, but please post if you're still having issues.

**Closed by tlancina** 2016-01-14 20:31 UTC
Labels: v2
